### ISSUE TITLE
Problems accessing multi asset based wallets on mobile

### ISSUE THREAD

**Issue by rdlrt** [Emurgo/yoroi-mobile#1567]
A user reported (on community tech support) an issue while trying to access his wallet on Yoroi mobile device after sending it a NFT:
```
unknown:ReactNative: Row too big to fit into CursorWindow requiredPos=0, totalRows=1
```

Unfortunately he does not have his mnemonics to try and access it from another wallet/CLI/etc so he is stuck waiting to be able to access his funds.

Logcat from android device

```
2021-08-22 14:03:36.524 22767-22849/? W/CursorWindow: Window is full: requested allocation 2241428 bytes, free space 2096658 bytes, window size 2097152 bytes
2021-08-22 14:03:36.524 22767-22849/? E/SQLiteQuery: exception: Row too big to fit into CursorWindow requiredPos=0, totalRows=1; query: SELECT key, value FROM catalystLocalStorage WHERE key IN (?)
2021-08-22 14:03:36.525 22767-22849/? W/unknown:ReactNative: Row too big to fit into CursorWindow requiredPos=0, totalRows=1
    android.database.sqlite.SQLiteBlobTooBigException: Row too big to fit into CursorWindow requiredPos=0, totalRows=1
        at android.database.sqlite.SQLiteConnection.nativeExecuteForCursorWindow(Native Method)
        at android.database.sqlite.SQLiteConnection.executeForCursorWindow(SQLiteConnection.java:1001)
        at android.database.sqlite.SQLiteSession.executeForCursorWindow(SQLiteSession.java:838)
        at android.database.sqlite.SQLiteQuery.fillWindow(SQLiteQuery.java:62)
        at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:153)
        at android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:140)
        at com.reactnativecommunity.asyncstorage.AsyncStorageModule$1.doInBackgroundGuarded(AsyncStorageModule.java:142)
        at com.reactnativecommunity.asyncstorage.AsyncStorageModule$1.doInBackgroundGuarded(AsyncStorageModule.java:119)
        at com.facebook.react.bridge.GuardedAsyncTask.doInBackground(GuardedAsyncTask.java:36)
        at com.facebook.react.bridge.GuardedAsyncTask.doInBackground(GuardedAsyncTask.java:20)
        at android.os.AsyncTask$3.call(AsyncTask.java:394)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at com.reactnativecommunity.asyncstorage.SerialExecutor$1.run(SerialExecutor.java:25)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
```

**Comment by realbluehead** [comment]
Is the same error reported a lot of times and not addressed.

**Comment by zuzunker** [comment]
Hi, @rdlrt! Thank you for providing the details and the logs especially!

We are now actively investigating this issue so the fix might be coming out soon.

**Comment by zuzunker** [comment]
@rdlrt , if you will see anyone reporting this issue as well, plz refer them to this issue now 🙌

**Comment by wolverineks** [comment]
@rdlrt how many transactions, nfts did the user have at the time of the issue?

**Comment by zuzunker** [comment]
@efegure @manupmt @realbluehead , moving the discussion here from https://github.com/Emurgo/yoroi-mobile/issues/1572

Can you plz provide some information on how many different token types or separate NFTs there have been in your wallet when you were trying to restore it in the mobile app?

**Comment by manupmt** [comment]
The problem occurs after having around 50 NFTs, I guess, but if yoroi can't sustain NFTs you should provide this service, anyway I've changed to desktop yoroi and is still verry verry slow, can't believe it, it's like a pc back in "95, I'm verry disappointed..to say the least

**Comment by zuzunker** [comment]
> but if yoroi can't sustain NFTs you should provide this service, anyway I've changed to desktop yoroi and is still verry verry slow

We are investigating and fixing these issues for both the mobile and the browser extension

**Comment by efegure** [comment]
@vsubhuman I have a total of 386 tokens in my wallet, I deleted the app twice and restored using my passphrase, first time opening the app works, after killing it and reopening it the error starts to happen.

**Comment by zuzunker** [comment]
Thank you, @efegure! We now have a fix candidate for it ready, if everything is good we might have it included in the next update

**Comment by wolverineks** [comment]
> @vsubhuman I have a total of 386 tokens in my wallet, I deleted the app twice and restored using my passphrase, first time opening the app works, after killing it and reopening it the error starts to happen.

makes sense.
reading from disk is the problem, and that doesn't happen until the second loading of a wallet.

**Comment by wolverineks** [comment]
on which versions of android are people experiencing the problem?

**Comment by zuzunker** [comment]
> on which versions of android are people experiencing the problem?

From here we know @efegure had it on 11: https://github.com/Emurgo/yoroi-mobile/issues/1572

From another user on Telegram I have also seen Pixel 4a with Android 11.

@manupmt @realbluehead, can you please clarify which version you are using?

@rdlrt , if you have any information on which versions people are reporting it from - that would help.

**Comment by rdlrt** [comment]
Apologies, somehow I overlooked notifications from this ticket 🙁 

> @rdlrt , if you have any information on which versions people are reporting it from - that would help.

I will ask others, but the 2 I know so far have been on Android 11 too - do we need specific build numbers?

**Comment by rdlrt** [comment]
Looks like all that I have conversation with from community TS had already upgraded to Android 11

**Comment by zuzunker** [comment]
> I will ask others, but the 2 I know so far have been on Android 11 too - do we need specific build numbers?

Thank you, @rdlrt ! No need for specific build versions

**Comment by efegure** [comment]
Hello @vsubhuman, is the new version with this update released yet ?

**Comment by zuzunker** [comment]
Hi, @efegure, it is not released yet, but is being prepared. Please look out for the version 4.4, this will be release in ~1-2 days from now, if all the testing goes well.
